# Generated by Django 5.0.3 on 2024-05-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='app',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='MapUserApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appdownload', models.ManyToManyField(blank=True, related_name='appdownloaded', to='adminuser.app')),
                ('userusing', models.ManyToManyField(blank=True, related_name='userusing', to='adminuser.user')),
            ],
        ),
    ]
