# Generated by Django 5.0.3 on 2024-05-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0002_adminmodel_remove_app_user_user_image_mapuserapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='points',
            field=models.CharField(max_length=50),
        ),
    ]
