# Generated by Django 5.0.3 on 2024-05-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0003_alter_app_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apps',
            field=models.ManyToManyField(blank=True, related_name='apps', to='adminuser.app'),
        ),
        migrations.DeleteModel(
            name='MapUserApp',
        ),
    ]
